# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170429_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='lat',
            field=models.FloatField(default=0.333),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='long',
            field=models.FloatField(default=0.333),
            preserve_default=False,
        ),
    ]
