# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='name',
            field=models.CharField(default='this step was before names', max_length=50),
            preserve_default=False,
        ),
    ]
